version: '2'

services:

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pass@word1

  wordpress:
    image: wordpress
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_PASSWORD: pass@word1

